### ISSUE TITLE
Week 4 Ready For Review

### ISSUE THREAD

**Issue by spartan7777** [spartan7777/ConceptCompendium#5]
@pawaitemadisoncollege Week 4 is complete. I did this work in my project, so it appears here. 
**What were your key learning points/takeaways?:** I took away a lot getting into working along with the 4 Demo videos to get Hibernate and all Java Classes working with Hibernate. I was able to see some of the logic behind the code (would not have come up with it though) and appreciate the time it took to get this assignment completed. Unit Testing and Test Driven Development has become a lot less intimidating. I see what is needed, I create methods to give me that, and then I check to see if I got what I was looking for. It came together nicely after spending a lot of time with it. 

**What challenged you?:** Time management for the week once again got in the way, but I was able to make up a bit of ground and get Week 4 done. The biggest challenge was getting unit tests to pass and trying to work back to find the errors that I made that caused the problems. 

**What problems did you solve and what resources did you use to solve them?:** I managed to solve the failing unit tests by doing a lot of research, re-watching the videos to make sure I had done things correctly, and then reached out for some assistance. After reaching out and seeing what others were dealing with, I was able to trace it to two database tables having different table names. I would have never thought that this could break so much down the line - but I appreciate that it happened.

**Comment by pawaitemadisoncollege** [comment]
Hi @spartan7777! I'm glad to hear more practice with TDD and unit testing is helping; I hope the same will be true with Hibernate, as you continue working with it in week 5 and beyond.  

Good work thoroughly testing your first Dao! 

- [ ] Might the CompendiumDaoTest be better named UserDaoTest since this test is related to Users? It's common practice to name each DaoTest for the entity that is being accessed most in that test.
- [ ] Verifying the entities are saved/updated/inserted correctly can be more thorough by implementing and using equals() on each entity - refer to the video Comparing Hibernate Entities with equals in week 5 for more detail.  An example of using that equals method in a unit test would be something like `assertTrue(expectedUser.equals(actualUser));` so that you don't have to compare each instance var/column manually like this: https://github.com/spartan7777/ConceptCompendium/blob/cf01627f900c1d985e1cfbee4784cfc61d67a537/src/test/java/ogedengbe/tosan/communication/CompendiumDaoTest.java#L68.
- [ ] I think this case https://github.com/spartan7777/ConceptCompendium/blob/cf01627f900c1d985e1cfbee4784cfc61d67a537/src/main/java/ogedengbe/tosan/communication/CompendiumDao.java#L41, could be covered by https://github.com/spartan7777/ConceptCompendium/blob/cf01627f900c1d985e1cfbee4784cfc61d67a537/src/main/java/ogedengbe/tosan/communication/CompendiumDao.java#L93?  It may not make sense to make this change though, as I would expect you'll convert over to the generic dao after completing the week 5 one-to-many exercise, but I did want to mention it in case you run into this kind of situation in the week 5 exercise.
