### ISSUE TITLE
Individual Project Checkpoint 2 Ready for Review

### ISSUE THREAD

**Issue by spartan7777** [spartan7777/ConceptCompendium#8]
@pawaitemadisoncollege Individual Project Checkpoint 2 is ready for review.  

Ms. Waite, I am submitting what I have for Checkpoint 2 at this time. It is a bit behind the deadline right now, and I do not want to keep it from review any further as the issues I have are going to take some time to complete. 

The requirements for this checkpoint were: 
1. Database designed and created.
2. At least one DAO with full CRUD (create, read, update, delete) implemented with Hibernate.
3. DAO is fully unit tested, Log4J is implemented. 

My submission for this checkpoint contains:
1. Database designed and created.
2. At least one DAO (Compendium DAO - modelled after the Generic Dao) with full CRUD (create, read, update, delete) implemented with Hibernate.
*3. My issue is with this item. I do not have the DAO completely unit tested as I am working on creating those tests (a battle with foolishly trying to make generic tests to go with a generic Dao). Log4J is implemented, but I do not have the tests ready, and I am working on getting my classes to start to work with my jsp pages - so there is not a lot to see there at this time.

**Comment by pawaitemadisoncollege** [comment]
Hi @spartan7777.  You had hit the Dao and unit testing item in week 4! 

A few other items needed though:

- [ ] Can you point me to the ERD for the database?
- [ ] Please update your project plan by checking off completed items and adding any new tasks to the plan as you discover them.

Other items I noticed, not necessarily related to CP2, that may already be on your radar, but that I don't want to get lost:

- [ ] Remember to use the jstl import tag to import single jsp "parts" rather than duplicating html such as the head tag.
- [ ] There's no need to put code or jsps in the various checkpoint folders. html and code should generally stay in their proper locations within the project - no need to copy them around.
- [ ] Rather than hard-coding drop down values like this< https://github.com/spartan7777/ConceptCompendium/blob/766686fcc8060f6e2fead5980c356feb4d1e1fd3/src/main/webapp/WEB-INF/JSPs/create.jsp#L35-L45, use a java bean and jstl such that this data is ultimately pulled from the database - I'm assuming you have a Category table? 
- [ ] Do not keep the pem file in GitHub, that would allow anyone who finds it to access your EC2 instance and potentially wreak havoc there!

**Comment by spartan7777** [comment]
Ms. Waite, here are the responses to the issues you brought up for Checkpoint 2. 
1. I have attached a screenshot to my project folder containing the ERD for the database. 
2. I have attached an update Project Plan with items showing as completed, or moved as needed. 
3. I will work on getting the Generic Dao integrated into the project. I have been spending time trying to figure out what controllers I need and how much "control" to give each of them. 
4. I have added the need to implement JSTL into the project plan.
5. I have removed all extra code from the Checkpoint files. These will no longer move or be copied. 
6. I do not have a Category Table. I had this as a column in the Concept Table. Since these are dropdown selections that users will make, I can see that they should best be pulled form a database than made to be a database entry every time. I have a few database alterations that need to be made, so this will be one of them. I can provide a new ERD once these changes are made. 
7. The .pem files have been removed from my repo.

**Comment by pawaitemadisoncollege** [comment]
Great work with your CP2-related updates @spartan7777.  A few things:

- [ ] You can check off completed items in GitHub markdown like this: `- [x]`. See below for how this renders.
- [x] a completed item 
- [ ] Since the project plan is a living document, I think this would be easiest to manage in a single location rather than having a copy in each checkpoint directory. The beauty of using a version control is that you can always see what the document looked like at any point in time.  Perhaps tagging your project at various key points would be helpful if you want to be able to see what the project state was for checkpoint 1, 2, etc.
- [ ] I can't remember if we chatted about this previously or not - have you thought about what api or restful web service you will implement with your project? This could be something as simple as javamail for contacting the admin...
